[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-evals"
version = "0.1.0"
description = "A lightweight library for evaluating language models"
readme = "simple-evals/README.md"
authors = [
    {name = "Graphcore Research", email = "info@graphcore.ai"}
]
license = {text = "MIT"}
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "numpy",
    "tqdm",
    "requests",
    "jinja2",
    "scipy",
]

[project.optional-dependencies]
openai = ["openai>=1.0.0"]
anthropic = ["anthropic>=0.5.0"]
humaneval = ["human-eval @ git+https://github.com/openai/human-eval.git"]

[project.scripts]
simple_evals = "simple_evals:main"

[tool.setuptools]
packages = ["simple_evals", "simple_evals.sampler"]
# Include all non-Python files in the package
include-package-data = true

[tool.setuptools.dynamic]
version = {attr = "simple_evals.__version__"}

[tool.setuptools.package-data]
"simple_evals" = ["**/*.json", "**/*.jsonl", "**/*.csv", "**/*.txt"]

# Custom build step to run our setup script
[tool.setuptools.cmdclass]
build_py = "build.BuildCommand" 