
name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        uv run --dev -- pytest tests/
    
    - name: Run tests from a git requirement
      run: |
        uv venv .venv-from-git
        source .venv-from-git/bin/activate
        uv pip install git+https://github.com/graphcore-research/package-simple-evals.git@${{ github.sha }}[dev]
        pytest tests/

